// Generated by https://quicktype.io

export interface Client {
  idCliente: number;
  nombre: string;
  direccion: string;
  telefono: string;
}

export interface AddClient {
  nombre: string;
  direccion: string;
  telefono: string;
}
