// Generated by https://quicktype.io

export interface Measure {
  idMedida: number;
  nombre: string;
  nombreCorto: string;
}
export interface AddMeasure {
  nombre: string;
  nombreCorto: string;
}
