// Generated by https://quicktype.io

export interface OrderDetails {
  Producto: string;
  descripcion: string;
  cantidad: number;
  precioUnitario: number;
  precioTotal: number;
}

export interface Order {
  idOrden: number;
  fecha: string;
  cliente: string;
  total: number | null;
}
