// Generated by https://quicktype.io

export interface Product {
  idProducto: number;
  nombre: string;
  descripcion: string;
  SKU: string;
}
export interface AddProduct {
  nombre: string;
  descripcion: string;
  SKU: string;
}
